---
# DO THE FOLLOWING IN THE COMMENTED LINES MANUALLY BEFORE EXECUTE THIS PLAYBOOK
# sudo yum install -y epel-release
# sudo yum install -y ansible
# sudo vi /etc/ansible/hosts
#       [mainhost]
#       mainhost ansible_ssh_host=<host_ip>
#       ssh-keygen
#       ssh-copy-id ~/.ssh/id_rsa.pub root@<host_ip>
# test ansible: ansible -m ping mainhost
# vi /etc/selinux/config
# SELINUX=permissive
# SELINUXTYPE=targeted
# * restart the node *
# !!! IMPORTANT: AFTER RUNNING THIS PLAYBOOK SET PASSWORD TO USER apalau: passwd apalau
#
- hosts: mainhost
  remote_user: root
  tasks:
  - name: ensure yum-utils is at the latest version
    yum: name=yum-utils state=latest
  - name: ensure python is at the latest version
    yum: name=python state=latest
  - name: download and install Vagrant 1.9.1 RPM
    yum: 
       name=https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.rpm
       state=present
  - name: install virtualboxrepo
    get_url: 
       dest=/etc/yum.repos.d/virtualbox.repo 
       url=http://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo
       force=yes 
  - name: ensure VirtualBox is at the latest version
    yum: name=VirtualBox state=latest
  - name: ensure dkms is at the latest version
    yum: name=dkms state=latest
  - name: ensure vim is at the latest version
    yum: name=vim state=latest
  - name: ensure man is at the latest version
    yum: name=man state=latest
  - name: ensure java 1.8 is installed
    yum: name=java-1.8.0-openjdk state=present
  - name: ensure net-tools is at the latest version
    yum: name=net-tools
  - name: Setup alternate SSH port
    lineinfile:
       dest: "/etc/ssh/sshd_config"
       regexp: "^Port"
       line: "Port 23033"
    notify: "Restart sshd"
  - name: Setup selinux for alternate SSH port
    seport:
       ports: "23033"
       proto: "tcp"
       setype: "ssh_port_t"
       state: "present"
  - name: ensure group admins is already created
    group:
       name: "admins"
       state: present
  - name: ensure user apalau exists
    user:
       name: apalau
       shell: /bin/bash
       comment: "Albert Palau"
       group: admins
       state: present
  - name: Allow 'admins' group to have password sudo
    lineinfile:
       dest: /etc/sudoers
       state: present
       insertafter: '^%wheel'
       line: '%admins ALL=(ALL) ALL'
  - name: remove root ssh login
    lineinfile:
       dest: /etc/ssh/sshd_config
       state: present
       regexp: '^#PermitRootLogin yes'
       line: 'PermitRootLogin no'
  - name: AllowGroups admins
    lineinfile:
       dest: /etc/ssh/sshd_config
       state: present
       insertafter: EOF
       line: 'AllowGroups admins'
    notify: "Restart sshd"

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted

