# This Ansible playbook install and configure a collectd
---
- name: Ensure all needed packages are present
  yum:
     name: '{{ item }}'
     state: present
  with_items:
  - '{{ packages_to_install }}'
  become: true
- name: Ensure collectd is running (and enable it at boot)
  service: name=collectd state=started enabled=yes
  become: true
- name: Configure collectd.conf
  template:
     src: collectd.conf.j2
     dest: /etc/collectd.conf
     mode: "u=rw,g=r,o=r"
     backup: yes
  become: true
  notify: Restart collectd
